#! /bin/sh

#startup apps
sxhkd -c ~/.config/sxhkd/sxhkdrc &
compton -f &
redshift &
mpd &
xautolock -locker "~/.config/i3/lock.sh" -time 5 -detectsleep -notify 5 &
feh --bg-fill ~/Pictures/wakanda_africa.jpg &
~/.config/polybar/polybarstart.sh &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
